const enum GlobalConstants {
    BUFF_UTILITY_SETTINGS = 'BuffUtility_Settings',
    BUFF_UTILITY_SETTINGS_AGREE_DANGER = 'BuffUtility_Settings_AgreeDanger',
    BUFF_UTILITY_CURRENCY_CACHE = 'BuffUtility_Currency_Cache',
    // BUFF_UTILITY_LOADED_EVENT = 'BuffUtility_Loaded',
    BUFF_UTILITY_INJECTION_SERVICE = 'BUFF_UTILITY_INJECTION_SERVICE',
    BUFF_UTILITY_OBJECT_SERVICE = 'BUFF_UTILITY_OBJECT_SERVICE',
    // BUFF_UTILITY_ASK_OBJECT = 'BUFF_UTILITY_ASK_OBJECT',
    BUFF_UTILITY_ASK_NARROW = 'BUFF_UTILITY_ASK_NARROW',
    BUFF_UTILITY_SIGNAL = 'BUFF_UTILITY_SIGNAL',
    BUFF_UTILITY_CUSTOM_CURRENCY = '---',
    BUFF_UTILITY_ID_HIDE_CUSTOM_FLOAT_BAR = 'BUFF_UTILITY_ID_HIDE_CUSTOM_FLOAT_BAR',
    BUFF_UTILITY_ID_EXPAND_CUSTOM_FLOAT_BAR = 'BUFF_UTILITY_ID_EXPAND_CUSTOM_FLOAT_BAR',

    SYMBOL_YUAN = '¥',
    SYMBOL_ARROW_UP = '▲',
    SYMBOL_ARROW_DOWN = '▼',

    COLOR_GOOD = '#009800',
    COLOR_BAD = '#c90000',
    COLOR_ORANGE = '#eea20e',
    COLOR_BLUE = '#0e87ee'
}
